name: Bumper
on:
  issue_comment:
    types: [created]

jobs:
  on-pr-comment:
    # Only run if the comment is on a pull request
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out your repository so you can run your script
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Install dependencies (assuming your Node.js project uses package.json)
      - name: Install dependencies
        run: npm ci

      # Step 3: Run your script
      - name: Run library script
        run: npm run bumper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          PR_COMMENT: ${{ github.event.comment.body }}
