name: Bumper

on:
  issue_comment:
    types: [created]

jobs:
  on-pr-comment:
    # Only run if the new comment is on a pull request
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Run library script
        run: node ./lib.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          PR_COMMENT: ${{ github.event.comment.body }}
