name: Bumper

on:
  issue_comment:
    types: [created]

permissions:
  contents: write   # Ensure we can read/checkout the fork code

jobs:
  on-pr-comment:
    if: ${{ github.event.issue.pull_request }}  # Only run if the comment is on a PR
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve PR branch via GitHub Script
        uses: actions/github-script@v6
        with:
          script: |
            // Get the PR number from the issue payload
            const prNumber = context.payload.issue.number;

            // Fetch PR details
            const { data: pr } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
            });

            // Export the head branch name as an environment variable
            core.exportVariable('BRANCH_NAME', pr.head.ref);

      - name: Check out PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Install dependencies
        run: npm ci

      - name: Run library script
        run: | 
          git rev-parse --abbrev-ref HEAD
          echo "========"
          # Set up Git configuration
          git config --global user.email "contato@mariosouto.com"
          git config --global user.name "Bumper"

          # Setup .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_REGISTRY_TOKEN }}" > ~/.npmrc

          # Run the bumper script
          npm run bumper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          PR_COMMENT: ${{ github.event.comment.body }}
          GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
