name: Bumper

on:
  issue_comment:
    types: [created]

permissions:
  contents: write   # Ensure we can read/checkout the fork code

jobs:
  on-pr-comment:
    if: ${{ github.event.issue.pull_request }}  # Only run if the comment is on a PR
    runs-on: ubuntu-latest

    steps:
      - name: Check out PR branch
        uses: actions/checkout@v3
        with:
          # Use the fork’s repo/branch if needed
          repository: ${{ github.event.issue.pull_request.head.repo.full_name }}
          # This is the branch name of the PR
          ref: ${{ github.event.issue.pull_request.head.ref }}
          # Fetch full history to ensure we are actually on the PR branch
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci

      - name: Run library script
        run: | 
          # Set up Git configuration
          git config --global user.email "contato@mariosouto.com"
          git config --global user.name "Bumper"

          # Setup .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_REGISTRY_TOKEN }}" > ~/.npmrc

          # Run the bumper script
          npm run bumper
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.issue.number }}
          PR_COMMENT: ${{ github.event.comment.body }}
          GH_REGISTRY_TOKEN: ${{ secrets.GH_REGISTRY_TOKEN }}
